### PR TITLE
Updating to use Go modules

### PR DESCRIPTION
**Pull request by sc250024**
# Description

Fairly simple PR; this removes the need to use `dep`, and favors instead using Go modules, which have been supported since Go 1.11. If you all really prefer to keep the `vendor` directory, I can use `go mod vendor` to re-initialize it.

### CODE REVIEW

**Comment by Bren2010** [comment]
Tbh I prefer to keep the dep-managed dependencies because I never bothered to learn how modules work!

**Comment by Bren2010** [comment]
Thank you, though!!

**Comment by sc250024** [comment]
> Tbh I prefer to keep the dep-managed dependencies because I never bothered to learn how modules work!

Ummmm .....

Screen Shot 2020-10-20 at 13 24 55

**Comment by acmcelwee** [comment]
@Bren2010, apart from the slightly aggressive response, I do have to agree w/ @sc250024 here. If this were 2018, there might still be some uncertainty around the future of (then `vgo`) go modules. At this point, all of the momentum around dependency management in golang does appear to have swung that direction, and it makes the out-of-the-box experience much more predictable for potential contributors to the project.

**Pull request closed without merging**
